<?php

namespace App\Controller;

use App\Enum\Language;
use App\Enum\MetaEntityType;
use App\Repository\MetaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class MetaController extends AbstractController
{
    #[Route('/meta/{type}/{id}/{lang}', name: 'meta_show')]
    public function index(
        MetaEntityType $type,
        int $id,
        Language $lang,
        MetaRepository $repo
    ): JsonResponse
    {
        $meta = $repo->findOneBy([
            'entityType' => $type,
            'entityId' => $id,
            'lang' => $lang,
        ]);

        if (!$meta) {
            return $this->json(null, Response::HTTP_NOT_FOUND);
        }

        $seoText = null;

        if ($meta->getEntityType() === MetaEntityType::Operator) {
            $seoText = $this->buildOperatorSeoText($lang, $meta->getEntityId());
        }

        return $this->json([
            'id' => $meta?->getId(),
            'entityType' => $meta?->getEntityType()?->value,
            'entityId' => $meta?->getEntityId(),
            'lang' => $meta?->getLang()?->value,
            'title' => $meta?->getTitle(),
            'description' => $meta?->getDescription(),
            'text' => $seoText,
        ]);
    }

    private function buildOperatorSeoText(Language $lang, int $operatorId): ?string
    {
        $url = sprintf('http://product:8000/operator/%d', $operatorId);

        $json = @file_get_contents($url);
        if ($json === false) {
            return null;
        }

        $data = json_decode($json, true);
        if (!is_array($data)) {
            return null;
        }

        $name = (string)($data['name'] ?? '');
        $sales = (int)($data['sales'] ?? 0);
        $routes = (int)($data['routes'] ?? 0);
        $rating = (float)($data['rating'] ?? 0.0);

        return match ($lang) {
            Language::EN => sprintf(
                'Amazing operator %s with %d sales, %d routes and rating %.1f. This is a demo SEO text generated by the SEO service.',
                $name,
                $sales,
                $routes,
                $rating
            ),
            Language::FR => sprintf(
                'Un opérateur formidable %s avec %d ventes, %d itinéraires et une note de %.1f. Ceci est un texte SEO de démonstration généré par le service SEO.',
                $name,
                $sales,
                $routes,
                $rating
            ),
            Language::ES => sprintf(
                'Un operador excelente %s con %d ventas, %d rutas y una calificación de %.1f. Este es un texto SEO de demostración generado por el servicio SEO.',
                $name,
                $sales,
                $routes,
                $rating
            ),
        };
    }
}
